Update README.md
thepolicylab-projectportals/projectportal-email-service pull request #13
Opened 2023-08-17 21:15 UTC by jashlu

2023-09-19 19:26 UTC, hetd54 requested changes

2023-09-19 19:26 UTC, hetd54 commented on README.md
> +The Personal Access Token is set up to expire after a specific period of time, requiring manual renewal by CCV personnel with access to the CCV CJ Bot.
When this PAT is regenerated, the email service needs to be re-deployed (see "Deploying the email-service")

2023-09-19 19:26 UTC, hetd54 commented on README.md
> +This [script](https://github.com/brown-ccv/k8s-deploy-bke/blob/main/deploy.sh) helps to automate the deploy process of the email-service. Simply run `./deploy.sh` and the script will run through a wi
Any changes to the email service files (updating secrets, changing the job timeline, etc.) requires the email service to be re-deployed with './deploy.sh'.

2023-12-21 18:58 UTC, jashlu commented
Updated README with additional instructions for RENCI handover means this readme is no longer relevant

2023-12-21 18:58 UTC, closed without merging